---
AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  AccountStagingBucketArn:
    Description: 'The name of the bucket used to stage lambda layers, lambda code, etc.'
    Value: !Ref 'AccountStagingBucket'
    Export:
      Name: 'AccountStagingBucketName'

Resources:
  AccountStagingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
    DeletionPolicy: 'Retain'
